project_id = "dqcvdgugqqvdjxjflwaq"

[functions.whatsapp-send]
verify_jwt = false

[functions.check-lembretes]
verify_jwt = false

[functions.run-campanhas]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.check-pos-atendimento]
verify_jwt = false
